#!/bin/bash

sumfile="/root/crontabsum"
file="/etc/crontab"
MD5SUM=`cat /root/crontabsum`
NEWSUM=`md5sum /etc/crontab | cut -d " " -f 1`

if [ ! -f "$sumfile" ]
then
	echo "$sumfile doest not exists. We create it."
   md5sum $file | cut -d " " -f 1 > $sumfile
else
	if [ "$MD5SUM" != "$NEWSUM" ]
	then
		if [ -x "$(command -v mail)"]
		then
			echo "Command mail doest not exist."
			sudo apt-get update && sudo apt-get install -y mailutils
		fi
		echo "$file has been modified."
		md5sum $file | cut -d " " -f 1 > $sumfile
		mail -s "The file crontab was modified" root@localhost.com < $file
	else
		echo "$file has not been modified."
	fi
fi

# add this line to /etc/crontab
# 0 0    0 * 0-6   root    sh [PathToThisFile]
